session_name: configuration
windows:
- name: home
  window_name: "\U0001F3E0"
  start_directory: $HOME
  focus: true
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - null
  - null
- name: neovim
  window_name: neovim
  start_directory: $HOME/.homesick/repos/neovim
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - null
  - null
- name: dot
  window_name: dot
  start_directory: $HOME/.homesick/repos/dot
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - null
  - null
- name: macos
  window_name: macos
  start_directory: $HOME/.homesick/repos/macos
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - null
  - null
- name: tmux
  window_name: tmux
  start_directory: $HOME/.homesick/repos/tmux
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - null
  - null
- name: chat
  window_name: chat
  start_directory: $HOME/.homesick/repos/chat
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - null
  - null
