session_name: configuration
windows:
- name: home
  window_name: "\U0001F3E0"
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - ''
  - ''
  start_directory: $HOME
- name: neovim
  window_name: neovim
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - ''
  - ''
  start_directory: $HOME/.homesick/repos/neovim
- name: dot
  window_name: dot
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - ''
  - ''
  start_directory: $HOME/.homesick/repos/dot
- name: macos
  window_name: macos
  layout: even-horizontal
  options:
    automatic-rename: off
  panes:
  - ''
  - ''
  start_directory: $HOME/.homesick/repos/macos
